# Generated by Django 4.0 on 2022-04-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_services"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
    ]
