# Generated by Django 4.0 on 2022-04-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_services_timestamp_services_visible_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                default="pending",
                max_length=64,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="coins_charged",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=20,
                null=True,
                verbose_name="coins_charged",
            ),
        ),
    ]
