# Generated by Django 4.0 on 2022-04-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_center", "0003_transaction_status"),
        ("service", "0004_alter_order_status_alter_services_coins_charged"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_center.transaction",
            ),
        ),
    ]
