# Generated by Django 4.0 on 2022-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
