# Generated by Django 4.0 on 2022-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_alter_notifications_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="read",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="status",
            field=models.CharField(max_length=64),
        ),
    ]
