# Generated by Django 4.0 on 2022-03-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_services"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services",
            old_name="provider_email",
            new_name="user",
        ),
    ]
