# Generated by Django 4.0 on 2022-04-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_provider_email_services_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Services",
        ),
    ]
