# Generated by Django 4.0 on 2022-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_coin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tier",
            field=models.IntegerField(default=0),
        ),
    ]
