# Generated by Django 4.0 on 2022-04-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_product_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tier",
            field=models.IntegerField(default=1),
        ),
    ]
