# Generated by Django 4.0 on 2022-04-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_coin_alter_customuser_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=20,
                null=True,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tier",
            field=models.IntegerField(default=1),
        ),
    ]
