# Generated by Django 4.0 on 2022-04-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_tier"),
        ("users", "0009_alter_product_price_alter_product_tier"),
    ]

    operations = []
