# Generated by Django 4.0 on 2022-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_merge_20220406_1332"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="coin",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=100, max_digits=20, null=True
            ),
        ),
    ]
