# Generated by Django 4.0 on 2022-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_loginrecord_alter_customuser_coin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
