# Generated by Django 4.0 on 2022-04-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                blank=True, default="unsolved", max_length=32, verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
    ]
