# Generated by Django 4.0 on 2022-03-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_alter_customuser_country_alter_customuser_lat_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="zip",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="zip"
            ),
        ),
    ]
