# Generated by Django 4.0 on 2022-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="sender email address",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="receiver email address",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=16,
                        max_digits=22,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "commission_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=16,
                        max_digits=22,
                        null=True,
                        verbose_name="commission_fee",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "service_type",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="type"
                    ),
                ),
            ],
        ),
    ]
