# Generated by Django 4.0 on 2022-04-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=20,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="commission_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=20,
                null=True,
                verbose_name="commission_fee",
            ),
        ),
    ]
