# Generated by Django 4.0 on 2022-04-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_center", "0002_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                blank=True,
                default="finished",
                max_length=64,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
