name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'gcivil-nyu-org/S2022-Team-4-repo'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: login
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_app_name : home-fix
        heroku_api_key: d9fd30af-92c8-4394-81dd-ed92100791f2
        heroku_email: 'yz7726@nyu.edu'
        branch: "main"
